# Generated by Django 5.1 on 2024-09-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('shop', '0004_characteristic_product_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_posts', to='shop.product'),
        ),
    ]
