# Generated by Django 4.2.20 on 2025-05-15 00:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='products/documents/', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Возможности использования'),
        ),
    ]
