# Generated by Django 4.2.20 on 2025-06-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_meta_description_product_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-часть на основе названия (будет сгенерирована автоматически)', max_length=255, unique=True),
        ),
    ]
