# Generated by Django 4.2.20 on 2025-06-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Будет сгенерирован из названия', max_length=255, null=True, unique=True),
        ),
    ]
