# Generated by Django 4.2.20 on 2025-06-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='URL-часть на основе названия; генерируется автоматически', max_length=255, unique=True),
        ),
    ]
