# Generated by Django 4.2.20 on 2025-06-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_slug'),
    ]

    operations = [
    ]
