# Generated by Django 4.2.20 on 2025-06-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20250701_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-часть на основе названия; генерируется автоматически', max_length=255, unique=True),
        ),
    ]
