# Generated by Django 4.2.20 on 2025-07-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='order',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(default='Default Slider', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.slider')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
